Merge pull request #121 in SWE/db-web-ui from bugfix/DB-240-as-a-user-i-want-to-create-objects to master
Squashed commit of the following:

commit ff3d92ce41eb88db6cd13d6d1ba66399aca7bb0f
Author: Rehan Syed Muhammad <b3ckstage@hotmail.com>
Date:   Wed Nov 16 14:00:26 2016 +0100

    Customising the UI for processing modal of creating domain object

commit 88da09e88c0b4af056a544116735fea292ca6dc3
Merge: 3cbdad6 ffb596c
Author: Tom Kalmijn <tom.kalmijn@ripe.net>
Date:   Tue Nov 15 17:24:08 2016 +0100

    Merge remote-tracking branch 'origin/bugfix/DB-240-as-a-user-i-want-to-create-objects' into bugfix/DB-240-as-a-user-i-want-to-create-objects

commit 3cbdad6a1245abedf15edbf944256883f7af0ddf
Author: Tom Kalmijn <tom.kalmijn@ripe.net>
Date:   Tue Nov 15 17:23:45 2016 +0100

    removed redundant property

commit ffb596c3a74c0cad5d1f3295bde85290fdffa72d
Author: Paul Etchells <etch@dhcp-21-176.ripe.net>
Date:   Tue Nov 15 16:38:31 2016 +0100

    scrolls to errors if there are any

commit c7f96d4e63ad869742d9002cb7bb78b4ccfde739
Author: Paul Etchells <etch@dhcp-21-176.ripe.net>
Date:   Tue Nov 15 14:45:39 2016 +0100

    removed conflict

commit fb14c69040cc04d7777adfcbddca45e8825f2b42
Merge: c40c8cb 6dc2a9d
Author: Paul Etchells <etch@dhcp-21-176.ripe.net>
Date:   Tue Nov 15 14:43:42 2016 +0100

    Merge branch 'master' into bugfix/DB-240-as-a-user-i-want-to-create-objects

commit c40c8cbb8ce03caa507e138923251780527f2ac2
Merge: 594ef56 76fc64a
Author: Paul Etchells <etch@dhcp-21-176.ripe.net>
Date:   Tue Nov 15 14:29:32 2016 +0100

    Merge branch 'DBF-56-auth-popup' into bugfix/DB-240-as-a-user-i-want-to-create-objects

commit 594ef56a862cf8ae5f68ed1bd9b6b322f4e6b824
Author: Paul Etchells <etch@dhcp-21-176.ripe.net>
Date:   Tue Nov 15 13:31:36 2016 +0100

    working modal whilst waiting for domain creation

commit b05dbbda5de5459cbe116a92a2978ade62637031
Author: Tom Kalmijn <tom.kalmijn@ripe.net>
Date:   Tue Nov 15 11:31:50 2016 +0100

    minor refactoring

commit 9f1e1c6d5e5ce61b2aa56632ca7c01280b5c6f8b
Author: Tom Kalmijn <tom.kalmijn@ripe.net>
Date:   Tue Nov 15 10:48:14 2016 +0100

    returning TOO_MANY_REQUESTS when posting with the domain object wizard twice

commit 62757a539feb4099d53897cd11e7e002d8897dc6
Author: Tom Kalmijn <tom.kalmijn@ripe.net>
Date:   Tue Nov 15 10:25:09 2016 +0100

    minor refactoring

commit 894f7f66c7dde8abca42755f11e6ff75bbdb68ab
Author: Tom Kalmijn <tom.kalmijn@ripe.net>
Date:   Mon Nov 14 17:19:45 2016 +0100

    added javadoc

commit 76fc64a46ed46cc72788c0dece97cd85e13f371e
Author: Paul Etchells <etch@dhcp-21-176.ripe.net>
Date:   Mon Nov 14 17:14:26 2016 +0100

    re-enabled all tests

commit 4c29011aa1be561174c9d9c4dceb7349ceebf3b0
Author: Paul Etchells <etch@dhcp-21-176.ripe.net>
Date:   Mon Nov 14 17:00:44 2016 +0100

    got some domain tests working but need more

commit afe36c949d297480a2e607a8b380810c7cf6fcb5
Author: Tom Kalmijn <tom.kalmijn@ripe.net>
Date:   Mon Nov 14 16:51:38 2016 +0100

    try to fix bug in getHostName method

commit 6dc2e1acec89b05b0d3661ed6169fe819a45bd78
Author: Tom Kalmijn <tom.kalmijn@ripe.net>
Date:   Mon Nov 14 16:36:45 2016 +0100

    try to fix bug in getHostName method

commit d45cd491ae6ff998b2d32c8b25f200517616cbd0
Author: Tom Kalmijn <tom.kalmijn@ripe.net>
Date:   Mon Nov 14 14:33:22 2016 +0100

    cookie used for stickyness now specifies path '/'

commit 56b323b92bec6af34541247eb837511311fdddba
Author: Tom Kalmijn <tom.kalmijn@ripe.net>
Date:   Mon Nov 14 14:24:08 2016 +0100

    reinstated extra cookie code to tell the proxy where to go to (stickiness)

commit 8ceddf5c7f337e68495bd1ebb29e110af7da0eb4
Author: Paul Etchells <etch@dhcp-21-176.ripe.net>
Date:   Mon Nov 14 10:26:19 2016 +0100

    added modal popup when w8ing 4 domain creation

commit e4683407552d027a561860fbb4e8f6dbb06957cc
Author: Tom Kalmijn <tom.kalmijn@ripe.net>
Date:   Mon Nov 14 10:24:11 2016 +0100

    processed some SonarLint feedback

commit 12d84c980ac4fd8fa327ad18deb8ba012d4f29f1
Author: Tom Kalmijn <tom.kalmijn@ripe.net>
Date:   Mon Nov 14 09:52:48 2016 +0100

    removed some more redundant code

commit 5c34b42bb1dcd7c0b1c78a1327b0024972abadc9
Author: Tom Kalmijn <tom.kalmijn@ripe.net>
Date:   Mon Nov 14 09:34:05 2016 +0100

    removed redundant code

commit 8f33abb041318a6161c5abeb166b6c4dc2e1a2a2
Merge: 1a90a8c 064c5b5
Author: Tom Kalmijn <tom.kalmijn@ripe.net>
Date:   Fri Nov 11 15:06:11 2016 +0100

    Merge remote-tracking branch 'origin/DBF-56-auth-popup' into bugfix/DB-240-as-a-user-i-want-to-create-objects

commit 064c5b5cbd71859cea728789f2011a4a4e9ba9f1
Author: Paul Etchells <etch@dhcp-21-176.ripe.net>
Date:   Fri Nov 11 14:48:36 2016 +0100

    pass source into maintainers directive

commit 1a90a8cf17794bab4b03293eb405af4238094c7a
Author: Tom Kalmijn <tom.kalmijn@ripe.net>
Date:   Fri Nov 11 12:02:57 2016 +0100

    fix compilation error

commit f1cf663ac23d8b401f18ca1a7546e212f0e9d80a
Merge: 750fdcd c1fe722
Author: Tom Kalmijn <tom.kalmijn@ripe.net>
Date:   Fri Nov 11 11:57:48 2016 +0100

    Merge remote-tracking branch 'origin/DBF-56-auth-popup' into bugfix/DB-240-as-a-user-i-want-to-create-objects

    # Conflicts:
    #	backend/src/main/java/net/ripe/whois/services/WhoisDomainObjectService.java
    #	frontend/app/scripts/updates/web/selectController.js

commit 750fdcd2cdd090187a609902449768f0838f0a4c
Merge: 1ecff47 4b7b62e
Author: Tom Kalmijn <tom.kalmijn@ripe.net>
Date:   Fri Nov 11 11:55:44 2016 +0100

    Merge remote-tracking branch 'origin/bugfix/DB-240-as-a-user-i-want-to-create-objects' into bugfix/DB-240-as-a-user-i-want-to-create-objects

commit 1ecff47db655d7a3bd20e447cd4bb456848cc177
Author: Tom Kalmijn <tom.kalmijn@ripe.net>
Date:   Thu Nov 10 16:42:33 2016 +0100

    added cookie to instruct proxy to route back to the same server (make it sticky)

commit 70934da35a014802e57698b3b2a4c6cc5c30537a
Author: Tom Kalmijn <tom.kalmijn@ripe.net>
Date:   Tue Nov 8 14:45:38 2016 +0100

    DB-240 first attempt to make batch updates execute asynchronously

commit c1fe72231c500d2d62a56a559c805603480c545a
Author: Paul Etchells <etch@dhcp-21-176.ripe.net>
Date:   Thu Nov 10 17:55:55 2016 +0100

    added proxy for serving ng rest calls

commit 4b7b62e1b7e34623e49f2698c7313ed07db551ed
Author: Tom Kalmijn <tom.kalmijn@ripe.net>
Date:   Thu Nov 10 16:42:33 2016 +0100

    added cookie to instruct proxy to route back to the same server (make it sticky)

commit f2b080d2cbde625c6485ec49a6bfd261bcf87dcd
Author: Paul Etchells <etch@dhcp-21-176.ripe.net>
Date:   Thu Nov 10 15:25:08 2016 +0100

    queries whois for existing domains

commit e762e0176b658071d962e1b6755570e1b7be0526
Merge: a30a2e5 13c1d76
Author: Paul Etchells <etch@dhcp-21-176.ripe.net>
Date:   Thu Nov 10 13:50:32 2016 +0100

    Merge branch 'mystuff' into DBF-56-auth-popup

commit a30a2e5c474d86d6fa36a2294cc57bc262b68bba
Merge: 19d1f07 cf09983
Author: Paul Etchells <etch@dhcp-21-176.ripe.net>
Date:   Thu Nov 10 13:00:22 2016 +0100

    Merge branch 'DBF-56-auth-popup' of ssh://bitbucket.ripe.net:7999/swe/db-web-ui into DBF-56-auth-popup

commit 13c1d76cb9d39edd83cc5b92ee7f39d3eec8b637
Author: Paul Etchells <etch@dhcp-21-176.ripe.net>
Date:   Thu Nov 10 12:55:50 2016 +0100

    more

commit cf09983e64e6cd48ec25459cd48e5298098eed90
Author: Edward Shryane <eshryane@ripe.net>
Date:   Wed Nov 9 17:16:38 2016 +0100

    workaround for undefined $document, just don't use it for now (failing tests)

commit 130771c3cef9fa937ee7fd4145ffe84368b5f27b
Merge: 65214e2 66079c8
Author: Edward Shryane <eshryane@ripe.net>
Date:   Wed Nov 9 16:45:25 2016 +0100

    Merge branch 'master' into DBF-56-auth-popup

commit 19d1f070a6d0ebcd5195859ebcb5f6b569a5e825
Author: Paul Etchells <etch@dhcp-21-176.ripe.net>
Date:   Wed Nov 9 12:05:55 2016 +0100

    tidying up

commit 65214e242ac08cb2a6c7734096ee27f9d28fc6bf
Author: Paul Etchells <etch@dhcp-21-176.ripe.net>
Date:   Tue Nov 8 13:41:17 2016 +0100

    debounce remote call. a bit of code cleaning.

commit 8d1dd286b7dfaa4f2e36d9602561dd63d6484abd
Author: Tom Kalmijn <tom.kalmijn@ripe.net>
Date:   Tue Nov 8 14:45:38 2016 +0100

    DB-240 first attempt to make batch updates execute asynchronously

commit e42d0242fc677755172748493558502c782af199
Author: Edward Shryane <eshryane@ripe.net>
Date:   Mon Nov 7 15:39:44 2016 +0100

    Enable new create domain wizard

commit ad0528e71bbfeb40fca8287530e6fd27b7479a22
Author: Edward Shryane <eshryane@ripe.net>
Date:   Mon Nov 7 15:39:27 2016 +0100

    Allow /17 prefix on create domain wizard

commit b82b91c390237d3df274333b03817fe79606af71
Merge: 45fd451 12daab7
Author: Edward Shryane <eshryane@ripe.net>
Date:   Mon Nov 7 14:35:00 2016 +0100

    Merge branch 'master' into DBF-56-auth-popup

commit 45fd4513325bc0042398cbc508e55c11538578a3
Author: Paul Etchells <etch@dhcp-21-234.ripe.net>
Date:   Fri Nov 4 16:31:48 2016 +0100

    moved metadata function into AttributeMetadataService

commit 237c361f3768813ce7e2d0a5faffbb86b957830c
Merge: ad678d6 5794c95
Author: Paul Etchells <etch@dhcp-21-234.ripe.net>
Date:   Fri Nov 4 16:06:54 2016 +0100

    Merge branch 'DBF-56-auth-popup' of ssh://bitbucket.ripe.net:7999/swe/db-web-ui into DBF-56-auth-popup

commit 5794c9548289e9d111158bb18c4404165174909a
Author: Thiago da Cruz <tdacruzper@ripe.net>
Date:   Fri Nov 4 15:38:17 2016 +0100

    tiny progress

commit ad678d6674414e2b641dfe5cb74d4a6d3107611e
Author: Paul Etchells <etch@dhcp-21-234.ripe.net>
Date:   Fri Nov 4 15:15:10 2016 +0100

    moved credential code into CredentialService

commit a7965deb9e10ef88952e6f83600de731478019c9
Author: Thiago da Cruz <tdacruzper@ripe.net>
Date:   Fri Nov 4 13:36:14 2016 +0100

    Move logic into the service.

commit 92e9fcbf7fa7ea7b5208f87749118a4f160add05
Author: Paul Etchells <etch@dhcp-21-234.ripe.net>
Date:   Fri Nov 4 10:48:45 2016 +0100

    moved validprefix event handling into controller

commit dcc04c1afa9337d20e7d12116d10de78c2f80b88
Merge: bc13895 d14c6ff
Author: Thiago da Cruz <tdacruzper@ripe.net>
Date:   Thu Nov 3 11:50:22 2016 +0100

    Merge branch 'master' into DBF-56-auth-popup

commit bc13895a3181302d6bd240a38aaab5cb2c7064e6
Merge: aee29fe c882017
Author: Edward Shryane <eshryane@ripe.net>
Date:   Wed Nov 2 09:56:12 2016 +0100

    Merge branch 'DBF-56-specify-a-prefix' into DBF-56-auth-popup

commit aee29fee82d18331d95f33c7c73619d153d87ea0
Author: Thiago da Cruz <tdacruzper@ripe.net>
Date:   Tue Nov 1 17:04:00 2016 +0100

    Check for exact match to get mnt-lower

commit 7d18de77951fb70a8a3e4fb5a27d695ea937ce8c
Author: Edward Shryane <eshryane@ripe.net>
Date:   Tue Nov 1 15:58:12 2016 +0100

    work in progress

commit eb86f5a045a1a542d4e934bee9ece54df9949d3b
Merge: 32c7051 56c6c42
Author: Edward Shryane <eshryane@ripe.net>
Date:   Tue Nov 1 09:22:08 2016 +0100

    Merge branch 'DBF-56-specify-a-prefix' into DBF-56-auth-popup

commit 32c705128c173fd561b60461a7c87da80380d09a
Author: Thiago da Cruz <tdacruzper@ripe.net>
Date:   Mon Oct 31 11:26:06 2016 +0100

    add service to check if same or more specific domain exists

commit 918f9a065ec84d413705d8261d1ef9be62b5f92f
Merge: 6240a12 eade628
Author: Thiago da Cruz <tdacruzper@ripe.net>
Date:   Fri Oct 28 13:26:37 2016 +0200

    Merge branch 'DBF-56-specify-a-prefix' into DBF-56-auth-popup

commit 6240a122ec7dacf22816179e27bb33bb1bdb2920
Author: Edward Shryane <eshryane@ripe.net>
Date:   Wed Oct 26 14:55:08 2016 +0200

    Add internal RIPE repository for whois-client dependency