replace wiremock with spring-test Wiremock adds a dependency on servlet-api, which causes integration tests to fail (java.lang.NoSuchMethodError: javax.servlet.ServletContext.addFilter) Inject RestTemplate so it can be mocked